version: "2"
services:
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:1.40
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
  artemis:
      container_name: artemis
      # image: quay.io/artemiscloud/activemq-artemis-broker:1.0.11
      image: vromero/activemq-artemis:2.16.0
      environment: 
        AMQ_USER: admin
        AMQ_PASSWORD: admin
        ARTEMIS_USERNAME: admin
        ARTEMIS_PASSWORD: admin
      ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
  # zookeeper:
  #   image: quay.io/strimzi/kafka:0.31.1-kafka-3.2.3
  #   command: [
  #       "sh", "-c",
  #       "bin/zookeeper-server-start.sh config/zookeeper.properties"
  #     ]
  #   ports:
  #   - "2181:2181"
  #   environment:
  #     LOG_DIR: /tmp/logs

  # kafka:
  #   image: quay.io/strimzi/kafka:0.31.1-kafka-3.2.3
  #   command: [
  #     "sh", "-c",
  #     "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
  #   ]
  #   depends_on:
  #   - zookeeper
  #   ports:
  #   - "9092:9092"
  #   environment:
  #     LOG_DIR: "/tmp/logs"
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    