{
 "title": "Porto EDA",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Goals Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_goal_total) / sum(com_redhat_metrics_shoot_total)"
    }
   ]
  },
  {
   "title": "Goals",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_goal_total)"
    }
   ]
  },
  {
   "title": "Games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_game_start_total)"
    }
   ]
  },
  {
   "title": "Ground Collision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_ground_collision_total)"
    }
   ]
  },
  {
   "title": "Pole Collision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_pole_collision_total)"
    }
   ]
  },
  {
   "title": "Goals per Player",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (player) (com_redhat_metrics_total{kind=\"goal\"}))",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Shoots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_shoot_total)"
    }
   ]
  },
  {
   "title": "Game Over",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_game_over_total)"
    }
   ]
  },
  {
   "title": "Head Collision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_head_collision_total)"
    }
   ]
  },
  {
   "title": "Collisions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_metrics_pole_collision_total) + sum(com_redhat_metrics_head_collision_total) + sum(com_redhat_metrics_ground_collision_total)"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (kind) (com_redhat_metrics_total))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Top 10 Users Ranking",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, max by (userName) (com_redhat_metrics_score))",
     "legendFormat": "{{userName}} "
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(com_redhat_metrics_total)" }
   ]
  },
  {
   "title": "Unique Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (user) (com_redhat_metrics_game_start_total))"
    }
   ]
  }
 ]
}