{{- if .Values.enabled }}
{{- if .Values.grafana.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-route
  namespace: {{ .Values.grafana_namespace }}
spec:
  host: 
  to:
    kind: Service
    name: grafana
  port:
    targetPort: grafana
  wildcardPolicy: None
{{- end }}
{{- end }}
