apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metrics-monitor
  namespace: hackhathon
  labels:
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - hackathon
  podMetricsEndpoints:
    - interval: 5s
      path: /q/metrics
      scheme: http
      targetPort: 8080
  selector:
    matchLabels:
      app: one-tap-soccer-event-consumer

