apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: event-consumer-app-monitor
  namespace: my-monitoring
  labels:
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - my-project
  podMetricsEndpoints:
    - interval: 10s
      path: /q/metrics
      scheme: http
      targetPort: 8080
  selector:
    matchLabels:
      app: one-tap-soccer-event-consumer

