{{- if .Values.enabled }}
{{- if .Values.prometheus }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prometheus.clusterrolebinding }}
  namespace: {{ .Values.prometheus_namespace }}
  labels:
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheus.clusterrole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceaccount }}
    namespace: {{ .Values.prometheus_namespace }}
{{- end }}
{{- end }}