{{- if .Values.enabled }}
{{- if .Values.monitoring.kafka }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: entity-operator-metrics
  namespace: {{ .Values.prometheus_namespace }}
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.kafka.namespace }}
  podMetricsEndpoints:
  - path: /metrics
    port: healthcheck
{{- end }}
{{- end }}