{{- if .Values.enabled }}
{{- if .Values.prometheus.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus-route
  namespace: {{ .Values.prometheus_namespace }}
spec:
  host: 
  to:
    kind: Service
    name: prometheus-operated
  port:
    targetPort: web
  wildcardPolicy: None
{{- end }}
{{- end }}
