{{- if .Values.enabled }}
{{- if .Values.prometheus }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.serviceaccount }}
  namespace: {{ .Values.prometheus_namespace }}
  labels:
    app: prometheus
{{- end }}
{{- end }}